
on:
  workflow_dispatch:

name: Release new version

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Release to DockerHub
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Bump version
        uses: anothrNick/github-tag-action@1.35.0
        env:
          WITH_V: true

      - name: Get new tag
        id: new_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.1.0

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.new_tag.outputs.tag }}
          release_name: ${{ steps.new_tag.outputs.tag }}
          body: ${{steps.build_changelog.outputs.changelog}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            peavers/selenium-java
          tags: |
            type=raw,value=${{ steps.new_tag.outputs.tag }}
            type=raw,value=latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Rollback if failure
        if: failure() && steps.create_release.outputs.id != ''
        uses: author/action-rollback@stable
        with:
          id: ${{ steps.create_release.id }}
          tag: ${{ steps.new_tag.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
